add vhost-net support
baidu/dperf pull request #459
Opened 2024-06-27 10:05 UTC by fkcrazy001

1. add vhost-net as kni support
2. bugfix of kni queue racing
3. del KNI_ENABLE macro, because we can support kni in all cases

2024-06-28 06:41 UTC, pengjianzhang commented
1. #include <rte_kni.h>   会不会在高版本DPDK编译不过？
2. 注释保持C风格
3. 局部变量保持在函数前面定义

逻辑还没细看，待补充

2024-06-28 07:20 UTC, fkcrazy001 commented
1. #include <rte_kni.h> 已修改为只在 kni.c 中包含， vhost-net 模块不需要，之前是从kni.c中拷贝过来忘记删除了
2-3 已修改

2024-06-28 07:20 UTC, fkcrazy001 commented
> 1. #include <rte_kni.h>   会不会在高版本DPDK编译不过？
> 2. 注释保持C风格
> 3. 局部变量保持在函数前面定义
> 
> 逻辑还没细看，待补充

1. #include <rte_kni.h> 已修改为只在 kni.c 中包含， vhost-net 模块不需要，之前是从kni.c中拷贝过来忘记删除了
2-3 已修改

2024-07-13 07:55 UTC, pengjianzhang requested changes

2024-07-13 07:55 UTC, pengjianzhang commented on src/port.h
> +    struct rte_ring *kni_ring;
kni_ring -> kni_mbuf_queue

2024-07-13 07:55 UTC, pengjianzhang commented on src/port.h
> +    void *kni;
/* kni or virtio_user */

2024-07-13 07:55 UTC, pengjianzhang commented on src/virtio-user.c
> +        .max_rx_pkt_len = ETHER_MAX_LEN,
compile error at DPDK 21.11.1

src/virtio-user.c:55:10: error: ‘struct rte_eth_rxmode’ has no member named ‘max_rx_pkt_len’; did you mean ‘max_lro_pkt_size’?
   55 |         .max_rx_pkt_len = ETHER_MAX_LEN,
      |          ^~~~~~~~~~~~~~
      |          max_lro_pkt_size
src/virtio-user.c:56:46: error: ‘DEV_RX_OFFLOAD_JUMBO_FRAME’ undeclared here (not in a function); did you mean ‘DEV_RX_OFFLOAD_TIMESTAMP’?
   56 |         .offloads = DEV_RX_OFFLOAD_TCP_LRO | DEV_RX_OFFLOAD_JUMBO_FRAME,
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                              DEV_RX_OFFLOAD_TIMESTA

2024-07-13 07:55 UTC, pengjianzhang commented on src/virtio-user.c
> +		return -1;
if/else needs to use {}

2024-07-13 07:55 UTC, pengjianzhang commented on src/virtio-user.c
> +	int ret;
Variables are sorted from small to large according to their sizeof(type)

2024-07-13 07:55 UTC, pengjianzhang commented on src/virtio-user.c
> +		rte_exit(EXIT_FAILURE, "dev config failed\n");
{}

2024-07-13 07:55 UTC, pengjianzhang commented on src/virtio-user.c
> +    int i = 0;
The variable is defined in the front part of the function

2024-07-13 07:55 UTC, pengjianzhang commented on src/virtio-user.c
> +        {
if ( xxx ) {

}

2024-07-13 07:55 UTC, pengjianzhang commented on src/virtio-user.c
> +        {
if (xxx) {
}

2024-07-13 07:55 UTC, pengjianzhang commented on src/virtio-user.c
> +	if (ret < 0)
if (xxx) {
}

2024-07-13 07:55 UTC, pengjianzhang commented on src/virtio-user.c
> +        rte_exit(EXIT_FAILURE, "macaddr get failed\n");
Alignment

2024-07-13 07:55 UTC, pengjianzhang commented on src/virtio-user.c
> +        rte_exit(EXIT_FAILURE, "macaddr get failed\n");
Alignment

2024-07-13 07:55 UTC, pengjianzhang commented on src/virtio-user.c
> +	printf("Port %u MAC: %02"PRIx8" %02"PRIx8" %02"PRIx8
don't printf

2024-07-13 07:55 UTC, pengjianzhang commented on src/virtio-user.c
> +	char vdev_args[VDEV_NAME_SIZE];
sort by size
alignment

2024-07-13 07:55 UTC, pengjianzhang commented on src/virtio-user.c
> +    int i, cnt, n = 0, send_n=0;
Each variable occupies one line and is assigned an initial value.

2024-07-13 07:55 UTC, pengjianzhang commented on src/virtio-user.c
> +     * core that holds queue 0 is in charge of this port's kni work
bad comment format 
```
/* 
 *
 * */
```

2024-07-13 07:57 UTC, pengjianzhang commented
The spaces at the end of the line need to be removed

2024-07-30 06:20 UTC, fkcrazy001 commented
才注意到评论。今天验证下这些问题

2024-07-30 11:24 UTC, fkcrazy001 commented on src/virtio-user.c
> +        .max_rx_pkt_len = ETHER_MAX_LEN,
已修改，卸载特性实际不需要，已经删除。

2024-07-30 11:25 UTC, fkcrazy001 commented on src/virtio-user.c
> +		return -1;
已修改

2024-07-30 11:25 UTC, fkcrazy001 commented on src/virtio-user.c
> +	int ret;
已修改

2024-07-30 11:30 UTC, fkcrazy001 commented
在我的vscode中，似乎没有对齐问题，我再研究下

2024-08-05 12:12 UTC, pengjianzhang commented
行尾还是有空格

2024-08-07 08:51 UTC, fkcrazy001 reviewed
alignment issues fixed

2024-08-07 08:51 UTC, fkcrazy001 commented on src/virtio-user.c
> +		return -1;
fixed

2024-08-07 08:51 UTC, fkcrazy001 commented on src/virtio-user.c
> +        rte_exit(EXIT_FAILURE, "macaddr get failed\n");
> Alignment

fixed

2024-08-07 08:51 UTC, fkcrazy001 commented on src/virtio-user.c
> +        rte_exit(EXIT_FAILURE, "macaddr get failed\n");
> Alignment

fixed

2024-08-07 08:51 UTC, fkcrazy001 commented on src/virtio-user.c
> +     * core that holds queue 0 is in charge of this port's kni work
> bad comment format
> 
> ```
> /* 
>  *
>  * */
> ```

fixed

2024-08-10 04:29 UTC, pengjianzhang commented
一些格式问题，请查邮箱

2024-08-12 02:04 UTC, pengjianzhang commented
还是有些行尾空格

2024-08-12 02:39 UTC, fkcrazy001 commented
已修改，将新的commit合并并重新提了一个pr。

https://github.com/baidu/dperf/pull/481

2024-08-12 02:46 UTC, closed without merging